### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by tbeswick96** [uksf/Website-Issues#102]
Add notifications (email, maybe TS as well) for when the following are made:
- [x] Requests
- [x] SR1 applications
- [x] Comments

Add to user settings options to opt out of notifications
- [x] Email
- [x] Teamspeak

Some notifications will remain forced (Promotions, transfers, assignments, etc)

**Comment by tbeswick96** [comment]
Notifications button (no notifs): https://goo.gl/SuUd2u
Notifications button (read notifs): https://goo.gl/eMGvb9
Notifications button (unread notifs, number shows count): https://goo.gl/iDi8Es

Notifications panel: https://goo.gl/ukHWLZ
- Each notif has an icon by type, the message, and time ago
- Each notif can also be click to take to area of interest, if link is added
- Unread notifs have a red dot to signify they are new.
- Unread notifs are marked as read when the panel is opened after a 3 second delay
- All notifs can be dismissed with the clear all button on top right of panel
- Notifs can be individually dismissed with the clear button on their card
- 10 notifs are loaded initially. 10 more at a time can be loaded by scrolling to bottom of panel
- Page scrolling is blocked whilst the panel is open
- Notifs are retrieved every minute
- Clicking anywhere on the page, or routing anywhere will close the panel

Notifications panel (no notifs): https://goo.gl/tN9Yhy

**Comment by frostebite** [comment]
seems good
