### ISSUE TITLE
Discord Channel update

### ISSUE THREAD

**Issue by Sakuria566** [uksf/Website-Issues#169]
Update the #lobby Channel with the following permissions:

Permissions change - 
Send Messages: +SR1, -Everyone
Manage Messages: +SR1,
Embed Links: +SR1, -Everyone
Attach Files: +SR1, -Everyone
Read Message History: +Everyone
Add Reactions: -Everyone

Delete message history.

Update Channel description-
Entrance Lobby - Welcome to UKSF. Find out more about us below. Invite link: https://discord.uk-sf.co.uk/

**Comment by tbeswick96** [comment]
Done
