### ISSUE TITLE
Information Systems (replace forums)

### ISSUE THREAD

**Issue by tbeswick96** [uksf/Website-Issues#2]
This was discussed a while back, but the general thought is that a forum in the traditional sense (like we currently have) is pointless as our main communication channels are slack and whatsapp.
Therefore the idea was not to have a forum. 

Instead we have areas each dedicated to a function:
- One where permanent information can be uploaded. This would be things like training documents, information, guides, etc. Permission to view is based on tags (only SR1 can see SR1 guide etc)
- One where announcements, news, events etc can be posted in a blog type fashion. Comments can be made on these.

### Add suggestions for other areas below. They should be explicitly different from any others.

**Comment by Alwandy** [comment]
news post will be a method. 
separate page for blogs? Utilize SLACK for public?

**Comment by tbeswick96** [comment]
Slack should not be public. Currently we are unable to invite more people to slack unless we pay, as the initial transfer involved inviting a lot of people. This apparently fucks up slacks automatic member size/invite tracking thing. If we can resolve this, we should use a similar system to the ACE slack, where you don't invite people, but provide a link that automatically invites them. @frostebite I was hoping you could look into this whenever possible.

 > news post will be a method.

Not interested in how it's implemented, it's the layout for the end user that matters from this.
The general idea is to have a page where all news, events, and information are posted in a blog style fashion. 
For permanent information such as training guides, mod guides etc, these should be locked behind member permissions (so only SR1 can see SR1 guide etc) and accessible only to members.

**Comment by Alwandy** [comment]
Something like this: 
https://stackstorm.com/2015/06/30/using-stackstorm-to-auto-invite-users-to-a-slack-organization/
https://slack.com/api/users.admin.invite?token=XXX&email=test@email.com&channels=C000000001,C000000002
 

@frostebite @tbeswick96
