### ISSUE TITLE
Roster and LOA

### ISSUE THREAD

**Issue by WordyK** [uksf/Website-Issues#3]
Currently the Roster system that is based on google docs is not working on the level of efficiency we would like. All the task on it are manual and need to be overseen by SR10 officers. 

**Roster**

- The new roster it to be clean and only display essential information about a person, This include rank, name and unit they belong to and year they joined. 

- Roster should be visible to all people with the rank of recruit or higher. Roster SHOULD NOT visible to anyone without the required rank. 

- Roster should have the ability to be edited bu the command, adding, changing and removing people from it. 

- Aim is for the roster to be automated in terms of checking how active certain people are. It should connect along with TeamSpeak and register when was their last visit. However this is not a must have. 

**LOA**

Right now we have no effective way of checking the LOA's effectively. LOA system needs to be more simple.

- LOA system will be tight into the roster. A member will be able to log in, go to the roster and they will see the full list of members. There would be a small icon next to each name where each member could click on their own icon. Automatically all members would be signed up for the operation. If a member know he will not be able to attend, he can click to the icon and his name will be marked red while all these who attend green.

- You will be able to change your LOA status from Sunday to Friday 12am GMT.  

More to be added.

**Comment by Alwandy** [comment]
Roster should be public. 

I disagree with people signing off from operations. Best option is to make them sign in. If deadline not reached, system will automatically check those who didn't sign in and if no LOA exists within timespan then automatically strike them while sending a report out to SR1 of list people that got a strike.

**Comment by WordyK** [comment]
> Roster should be public.

Roster will have information about our members and who is part of us, this infromation should not be public because nobody outside really needs or should see it. If another unit request a look at it or request some information from it, that could be given to them by one of the command members. Other than that, roster should be closed off and only people that should see it are the UKSF members. 

> I disagree with people signing off from operations. Best option is to make them sign in.

No, because as the unit and people who provide the experience we should assume everyone will attend. Not attending is not suppose to be common. Its suppose to be once in a while thing. By signing up for the operation instead of signing off we will give a message to people that LOA is a good thing. I very heavily disagree with this and strongly suggest we keep to signing off the operation.

**Comment by tbeswick96** [comment]
> I disagree with people signing off from operations.

>No, because as the unit and people who provide the experience we should assume everyone will attend. Not attending is not suppose to be common. Its suppose to be once in a while thing. By signing up for the operation instead of signing off we will give a message to people that LOA is a good thing. I very heavily disagree with this and strongly suggest we keep to signing off the operation.

Yes it was previously decided by SR10 that assuming people are going to turn up and if they are not they have to sign off from the operation(s) is the system to be implemented.
