### ISSUE TITLE
Information Systems

### ISSUE THREAD

**Issue by frostebite** [uksf/Website-Issues#6]
See original post:
https://github.com/uksf/website-issues/issues/2

Out core information sharing plan:
- We won't be having a core forum system. They don't really suit our community and tend to be used to do things manually in other communities such as keeping a sticky roster post up to date.
- We do need a place to post official documents about the unit. 
- We do need a place to post announcements.
- Discord and teamspeak provide sufficient sufficient community communication platforms.

Remaining questions:
- Are we in agreement with our core plan?
- Where do we need commenting ability? Who should be able to comment? Who can/is responsible for administering?
- Is any direct messaging functionality needed on the website?
- Should announcements be pulled from Discord or made on the website?
- Where should announcements on the website be propagated to? (Discord/Website/Email)?

**Comment by tbeswick96** [comment]
I agree with the core plan.

- With regards to official documents, these should be behind group-walls...so only air can see air docs, PF see PF docs etc. That is, if we don't want to pursue the idea of open sourcing aspects of training.
- As for announcements, we could leave discord as the place for immediate announcements like there i an op happening, and use the website for the rest. For example, a change in SOP, modpack update, upcoming event etc.
- Comments could be allowed if each announcement links to its own subpage. (To reduce clutter)
- Maybe a case by case basis for approval to post. For example Stanton might want to make a post regarding a new youtube video.
- I think DM ability on website would be useful to have as an option, although not a primary.
- I don't think having announcements from discord to website is necessary if we choose the model of immediate on discord (op announcements, training, whatever), and the rest on website. However, website to discord would be useful. A link would be sufficient.

**Comment by frostebite** [comment]
> With regards to official documents, these should be behind group-walls...so only air can see air docs, PF see PF docs etc. That is, if we don't want to pursue the idea of open sourcing aspects of training.

Agreed

>As for announcements, we could leave discord as the place for immediate announcements like there i an op happening, and use the website for the rest. For example, a change in SOP, modpack update, upcoming event etc.
Surely, 
- a change in SOP - should be announced on the site.
- modpack update - should be announced on the site.
- upcoming event - should be automatically announced from the site to discord.

>Comments could be allowed if each announcement links to its own subpage. (To reduce clutter)

Agreed

>Maybe a case by case basis for approval to post. For example Stanton might want to make a post regarding a new youtube video.

Sure, this is fine. I meant more like the comments?

>I think DM ability on website would be useful to have as an option, although not a primary.

If it isn't primary, is there much point? We already have discord on top of this?

>I don't think having announcements from discord to website is necessary if we choose the model of immediate on discord (op announcements, training, whatever), and the rest on website. However, website to discord would be useful. A link would be sufficient.

Agreed.

**Comment by tbeswick96** [comment]
> Surely,...

Yeah those were examples for what would be posted on the website.

> Sure, this is fine. I meant more like the comments?

Ah sure so I guess whoever made the post and "admins", however they are defined. Could generalise as SR10 group, or just select individuals case by case


> If it isn't primary, is there much point? We already have discord on top of this?

It's just a redundancy in-case people can't access discord for whatever reason

**Comment by AnAngrySalad1** [comment]
Only addition I have to this is to make who's visible in TS behind a member wall. Don't really like the idea of people being able to come to the site and see all and everyone who's in TS.

**Comment by frostebite** [comment]
@tbeswick96 
>Yeah those were examples for what would be posted on the website.
so what goes on discord?

>It's just a redundancy in-case people can't access discord for whatever reason
it should be required probably no?

**Comment by frostebite** [comment]
@AnAngrySalad1 
Hmm, it is pretty common to have open? And they can just connect and see instantly anyway?
They can even go to teamspeak viewer and see it?
