### ISSUE TITLE
Recruitment workflow

### ISSUE THREAD

**Issue by frostebite** [uksf/Website-Issues#7]
See old post:
#1 

The current flow:
 - The current flow has applicants needing to do the following before they can create an application: create an account, connect teamspeak and connect steam.
 - The application includes the following fields: firstname, lastname, date of birth, home nation, hasMilitaryExperience, How long have they been playing arma, How much experience do they have with arma units, personal background information, are they interested in nco leadership/officer leadership/aviation, who referred them and agree to terms and conditions.
 - Once they create an application it is assigned to the recruiter with fewest in progress applications.
 - The recruiter can then comment.
 - The recruiter can rate on the following fields : http://prntscr.com/hkb3pk.png
 - The recruiter can accept or reject.

The suggested flow we are planning on:
 - An application must be approved by the SR1 recruiter, an SR1 lead and an SR10 operator.
 - SR1 leads can reassign apps.
 - Fields to rate applications on can be changed at any time by an SR1 lead.
 - Applicant can comment on his waiting application and the reviewers can also reply.
 - Applicant can view basic info about his in progress application.
 - SR1 members can step out, so no applications are assigned to themselves for when they are on holiday.

**Comment by tbeswick96** [comment]
I'm fine with this

For the assignment to SR1 with lowest applicants...this will also need to include the option for SR1 to disable themselves (SR1 lead and SR10 can do same). This has been useful in my google sheets setup for when people go on holiday or just don't have time to take applicants at that time.

**Comment by frostebite** [comment]
>For the assignment to SR1 with lowest applicants...this will also need to include the option for SR1 to disable themselves (SR1 lead and SR10 can do same). This has been useful in my google sheets setup for when people go on holiday or just don't have time to take applicants at that time.

Accepted and added to OP.

Question:
Could they potentially not just be removed from SR1 for this period?

**Comment by tbeswick96** [comment]
Possibly.
I think just a disable option would be better though, as it allows finer control.
