### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by tbeswick96** [uksf/Website-Issues#81]
- Look into ssl usage & cost

**Comment by tbeswick96** [comment]
- Possible to do through azure portal (App Service Certificate)
- Basic costs £50 a year

**Comment by mshaugh** [comment]
https://letsencrypt.org/

**Comment by tbeswick96** [comment]
Site now on kubernetes, possibly easier to do this now
https://kubernetes.io/docs/concepts/cluster-administration/certificates/
